import Foundation

struct Quote: Identifiable, Codable {
    let id: UUID
    let text: String
    let author: String
    
    static let quotes = [
    Quote(id: UUID(), text: "The only bad workout is the one that didn't happen.", author: "Unknown"),
    Quote(id: UUID(), text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
    Quote(id: UUID(), text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill"),
    Quote(id: UUID(), text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson"),
    Quote(id: UUID(), text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
    Quote(id: UUID(), text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis"),
    Quote(id: UUID(), text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
    Quote(id: UUID(), text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis"),
    Quote(id: UUID(), text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson"),
    Quote(id: UUID(), text: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
    Quote(id: UUID(), text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau"),
    Quote(id: UUID(), text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller"),
    Quote(id: UUID(), text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson"),
    Quote(id: UUID(), text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett"),
    Quote(id: UUID(), text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt"),
    Quote(id: UUID(), text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
    Quote(id: UUID(), text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs"),
    Quote(id: UUID(), text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky"),
    Quote(id: UUID(), text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford"),
    Quote(id: UUID(), text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown"),
    Quote(id: UUID(), text: "Don't stop when you're tired. Stop when you're done.", author: "Marilyn Monroe"),
    Quote(id: UUID(), text: "Dream it. Wish it. Do it.", author: "Unknown"),
    Quote(id: UUID(), text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown"),
    Quote(id: UUID(), text: "The key to success is to focus on goals, not obstacles.", author: "Unknown"),
    Quote(id: UUID(), text: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.", author: "Chantal Sutherland"),
    Quote(id: UUID(), text: "Your limitation—it's only your imagination.", author: "Unknown"),
    Quote(id: UUID(), text: "Push yourself, because no one else is going to do it for you.", author: "Unknown"),
    Quote(id: UUID(), text: "Great things never come from comfort zones.", author: "Unknown"),
    Quote(id: UUID(), text: "Dream it. Believe it. Build it.", author: "Unknown"),
    Quote(id: UUID(), text: "Success is what happens after you have survived all your mistakes.", author: "Anora Lee"),
    Quote(id: UUID(), text: "Don't wait for opportunity. Create it.", author: "George Bernard Shaw"),
    Quote(id: UUID(), text: "The secret of getting ahead is getting started.", author: "Mark Twain"),
    Quote(id: UUID(), text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon"),
    Quote(id: UUID(), text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney"),
    Quote(id: UUID(), text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill"),
    Quote(id: UUID(), text: "Don't limit your challenges. Challenge your limits.", author: "Unknown"),
    Quote(id: UUID(), text: "The harder the battle, the sweeter the victory.", author: "Les Brown"),
    Quote(id: UUID(), text: "Success is not in what you have, but who you are.", author: "Bo Bennett"),
    Quote(id: UUID(), text: "Your passion is waiting for your courage to catch up.", author: "Isabelle Lafleche"),
    Quote(id: UUID(), text: "Magic is believing in yourself, if you can do that, you can make anything happen.", author: "Johann Wolfgang von Goethe"),
    Quote(id: UUID(), text: "Don’t wait for the perfect moment. Take the moment and make it perfect.", author: "Zoey Sayward"),
    Quote(id: UUID(), text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar"),
    Quote(id: UUID(), text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe"),
    Quote(id: UUID(), text: "The future depends on what you do today.", author: "Mahatma Gandhi"),
    Quote(id: UUID(), text: "Act as if what you do makes a difference. It does.", author: "William James"),
    Quote(id: UUID(), text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer"),
    Quote(id: UUID(), text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman"),
    Quote(id: UUID(), text: "Opportunities don't happen. You create them.", author: "Chris Grosser"),
    Quote(id: UUID(), text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett"),
    Quote(id: UUID(), text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh"),
    Quote(id: UUID(), text: "Believe you deserve it and the universe will serve it.", author: "Lailah Gifty Akita"),
    Quote(id: UUID(), text: "You are capable of amazing things.", author: "Unknown"),
    Quote(id: UUID(), text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn"),
    Quote(id: UUID(), text: "Stay positive, work hard, make it happen.", author: "Unknown"),
    Quote(id: UUID(), text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier"),
    Quote(id: UUID(), text: "Don't give up. Great things take time.", author: "Unknown"),
    Quote(id: UUID(), text: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
    Quote(id: UUID(), text: "Great things never come from comfort zones.", author: "Unknown"),
    Quote(id: UUID(), text: "Dream it. Wish it. Do it.", author: "Unknown"),
    Quote(id: UUID(), text: "Stay focused and never give up.", author: "Unknown")
]
} 